### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zxsleebu** [Lemons1337/Blob.io-Bots#2]
C:\Users\IAMGOD\Desktop\Blob.io-Bots-master\node_modules\proxy-agent\node_modules\https-proxy-agent\index.js:185
      throw new Error('should not happen...');
      ^

Error: should not happen...
    at ClientRequest.onsocket (C:\Users\IAMGOD\Desktop\Blob.io-Bots-master\node_modules\proxy-agent\node_modules\https-proxy-agent\index.js:185:13)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at tickOnSocket (_http_client.js:655:7)
    at onSocketNT (_http_client.js:694:5)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by zxsleebu** [comment]
It happens after 5 minutes using bots
